### PR TITLE
fix: `make clean` command

### PR DESCRIPTION
**Pull request by da-bao-jian**

### CODE REVIEW

**Review by zsluedem — APPROVED** [review]
LGTM

**Comment by da-bao-jian** [comment]
> LGTM

cool

Just rebased two commits into one

Thanks for the tip

**Comment by Vid201** [comment]
LGTM. @da-bao-jian 

Just sync with main branch and CI should pass then, after that we can merge

**Comment by da-bao-jian** [comment]
Looks like the CI is still failing. 

Do I need to update my own branch to include the new .github/workflows? Not sure if the check is run based on the Silius/main or my forked branch.

**Comment by Vid201** [comment]
> Looks like the CI is still failing.
> 
> Do I need to update my own branch to include the new spec tests? Not sure if the check is run based on the Silius/main or my forked branch.

You should rebase `qi-protocol:fix/make-clean` branch on your repo (to include latest commits, that branch is 2 commits behind), and the CI will be rerun again when new commits are on that branch.

**Pull request merged**
