### PR TITLE
Doc: Rustdoc for the crate/uopool

### PR DESCRIPTION
**Pull request by da-bao-jian**
Created the Rustdoc for the uopool crate

### CODE REVIEW

**Review by Vid201 — APPROVED** [review]
LGTM! Thanks @da-bao-jian , rust docs are advancing good

**Comment by Vid201** [comment]
It seems there are some problems with CI. @zsluedem do you know maybe what's the problem?

**Comment by zsluedem** [comment]
Very wired. Sometimes I could reproduce it locally. Very strange bug. None production codes are changed.

**Comment by zsluedem** [comment]
@da-bao-jian We fixed the the problem. But you need to rebase and push again.

**Comment by Vid201** [comment]
> @da-bao-jian We fixed the the problem. But you need to rebase and push again.

@da-bao-jian we also merged the db reputation PR, which changes some things in this crate (sorry for that). if you want, you can add docs for db reputation as well, or I can add it later, as you wish

**Comment by da-bao-jian** [comment]
> > @da-bao-jian We fixed the the problem. But you need to rebase and push again.
> 
> @da-bao-jian we also merged the db reputation PR, which changes some things in this crate (sorry for that). if you want, you can add docs for db reputation as well, or I can add it later, as you wish

Sounds great. 

I'll add the doc

**Pull request merged**
